services:
  db:
    image: postgres:15
    container_name: django_postgresql
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=django_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - db

  backend:
    build: ./Django
    container_name: django_backend
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Django:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - POSTGRES_NAME=django_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    depends_on:
      - db

  # frontend:
  #   build: ./velzonreact
  #   container_name: react_frontend
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./velzonreact:/app
  #   environment:
  #     - WATCHPACK_POLLING=true
